addons:
  apt:
    packages:
    - stunnel
language: java
jdk:
  - oraclejdk8
install: make prepare ssl-keys
script: make test-coveralls
sudo: false
cache:
  directories:
    - '$HOME/.m2/repository'
